### ISSUE TITLE
RFE: WBFM has 15KHz of audio bandwidth, a 8000sp/s sampling rate crushes it to an ear-wrenching 4KHz

### ISSUE THREAD

**Issue by calimeroteknik** [wizardyesterday/RtlSdrDiags#61]
I have interest in this project because of the automatic gain control (AGC).
But it all falls apart when the audio is butchered at the demodulator!

WBFM has 15KHz of audio bandwidth, which means its Nyquist frequency is a 30KHz sample rate (maybe pick 32KHz, as it's a widespread standard).

The current demodulator uses 8KHz sampling rate, which crops the audio to… 4KHz!
It sounds like a bad laptop speaker placed in a tin can. Slightly worse sound than even USB ham radio on a 5KHz-wide carrier and therefore sound bandwidth.

**Comment by wizardyesterday** [comment]
Not so much the demodulators. I decimate the demod output to achieve the
audio sample rate of 8000S/s. This provides a consistant PCM sample rate
across all demod modes, by design.
The goal was to achieve voice quality audio, similar to that of a police
scanner.

This also allows me to change demod modes on the fly without having to
exit/relaunch the app in order to change demod modes.

Kind regards,
Chris G.

**Comment by wizardyesterday** [comment]
This software will remain the same. Maybe, I will create a new system that uses a higher audoo sple rate, though. I'll thinl about a system design.
