### ISSUE TITLE
Question - Where's the mixer gain control?

### ISSUE THREAD

**Issue by calimeroteknik** [wizardyesterday/RtlSdrDiags#64]
The RTL-SDR tuner has three gain settings, in the order of the signal processing chain:
 - the LNA gain, straight after the antenna or upconverter;
 - the mixer gain, which controls an amplifier between the LNA+tracking filter, and the heterodyne;
 - and the IF gain, which controls an amplifier between the heterodyne+PP filter, and the output of the tuner fed into the RTL2832U for digitization.
 
 I speculate that:
  - the LNA gain is controlled by `set rxgain` in this project;
  - the IF gain is controlled by `set rxifgain` in this project.
  
  What about the mixer gain? Is it controlled by hardware AGC after using the command `enable agc`, or…?

**Comment by wizardyesterday** [comment]
Hi.
The rxgain (both LNA and mixer) is modified by the set_gain() function. I
always set them to auto so that the LNA and mixer agc functions are
enabled. The set_if_gain() function sets the gain of the VGA (really an IF
amplifier). This amplifier gain can only be manually changed. I had
modified the library code (librtlsdr.cand tuner_r82xx.c) to provide support
for my software-based VGA (IF) AGC. The default library sets the VGA to
fixed values.

I hope this explaination helps to clarify things.

Kind regards,
Chris G.
